# Index ile Elemanlara Erişmek

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 3, 9, 9, 0, 0, 1, 8, 0, 7])

In [2]:
a[0]

6

In [3]:
a[-1]

7

In [4]:
a[0] = 100

In [5]:
a

array([100,   3,   9,   9,   0,   0,   1,   8,   0,   7])

In [6]:
m = np.random.randint(10, size = (3,5))
m

array([[9, 9, 5, 9, 3],
       [0, 6, 0, 6, 6],
       [7, 3, 3, 8, 7]])

In [7]:
m[0,0]

9

In [8]:
m[1,1]

6

In [9]:
m[1, 4]

6

In [10]:
m[1, 4] = 99

In [11]:
m

array([[ 9,  9,  5,  9,  3],
       [ 0,  6,  0,  6, 99],
       [ 7,  3,  3,  8,  7]])

In [12]:
m[1,4] = 2.2

In [13]:
m

array([[9, 9, 5, 9, 3],
       [0, 6, 0, 6, 2],
       [7, 3, 3, 8, 7]])