# NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [6]:
#sifirdan array olusturma 

In [7]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [11]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
np.random.normal(10, 4, (3,4))

array([[ 7.29873709,  5.43112002,  5.85550398, 10.40969572],
       [ 9.34785548,  0.04477872, 21.7960281 ,  3.61904922],
       [12.49094153,  6.27452227,  4.20539147, 13.85744392]])

In [13]:
np.random.randint(0,10, (3,3))

array([[9, 9, 4],
       [7, 2, 6],
       [5, 7, 5]])