# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [8]:
#iki boyutlu array siralama

In [9]:
m = np.random.normal(20,5, (3,3))

In [10]:
m

array([[11.34367936, 22.35139823, 22.98999717],
       [21.13617144, 15.473761  , 22.11736664],
       [34.0787152 , 16.0944836 , 19.44433187]])

In [11]:
np.sort(m, axis = 1)

array([[11.34367936, 22.35139823, 22.98999717],
       [15.473761  , 21.13617144, 22.11736664],
       [16.0944836 , 19.44433187, 34.0787152 ]])

In [12]:
np.sort(m, axis = 0)

array([[11.34367936, 15.473761  , 19.44433187],
       [21.13617144, 16.0944836 , 22.11736664],
       [34.0787152 , 22.35139823, 22.98999717]])