# Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[1, 2, 1, 2, 8],
       [3, 9, 2, 4, 9],
       [7, 3, 5, 1, 3],
       [6, 1, 0, 6, 8],
       [2, 7, 9, 9, 1]])

In [2]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 2],
       [3, 9],
       [7, 3]])

In [4]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [5]:
alt_a

array([[99999,     2],
       [    3,   888],
       [    7,     3]])

In [6]:
a

array([[99999,     2,     1,     2,     8],
       [    3,   888,     2,     4,     9],
       [    7,     3,     5,     1,     3],
       [    6,     1,     0,     6,     8],
       [    2,     7,     9,     9,     1]])

In [7]:
m = np.random.randint(10, size = (5, 5))
m

array([[0, 5, 2, 6, 8],
       [1, 7, 8, 7, 7],
       [3, 2, 1, 1, 9],
       [5, 0, 9, 2, 8],
       [4, 4, 6, 0, 7]])

In [8]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[0, 5],
       [1, 7],
       [3, 2]])

In [9]:
alt_b[0,0] = 9999

In [10]:
alt_b

array([[9999,    5],
       [   1,    7],
       [   3,    2]])

In [11]:
m

array([[0, 5, 2, 6, 8],
       [1, 7, 8, 7, 7],
       [3, 2, 1, 1, 9],
       [5, 0, 9, 2, 8],
       [4, 4, 6, 0, 7]])